---
- name: Install and Configure CommVault
  hosts: all

  vars:

  tasks:

  - name: Update Yum Configuraiton
    import_role:
      name: configure-yum
    tags: install

  - name:  Install Commvault (Standard Version)
    become: yes
    yum:
      name: cvlt-fs.Instance001
      state: present
      enablerepo: cbi-aws
      disable_gpg_check: yes
    register: cvaultinstalled
    notify:
      - start commvault
    when:
      - ('tag_AnsibleRoles_sap-hana' not in group_names)
      - ('tag_AnsibleRoles_oracle-database' not in group_names)
    tags: install

  - name: Notify commvault handler (non-Aamzon Linux)
    command: /bin/true
    notify: commvault
    when: ansible_distributio != "Amazon"

  - name:  Install Commvault (Hana DB version)
    become: yes
    yum:
      name: cvlt-hana-fs.Instance001
      state: present
      enablerepo: cbi-aws
      disable_gpg_check: yes
    register: cvaultinstalled
    notify:
      - start commvault
    when:
      - ('tag_AnsibleRoles_sap-hana' in group_names)
    tags: install

  - name:  Install Commvault (Oracle Version)
    become: yes
    yum:
      name: cvlt-ora-fs.Instance001
      state: present
      enablerepo: cbi-aws
      disable_gpg_check: yes
    register: cvaultinstalled
    notify:
      - start commvault
    when:
      - ('tag_AnsibleRoles_sap-hana' not in group_names)
      - ('tag_AnsibleRoles_oracle-database' in group_names)
    tags: install

  - name: Check status of properties file
    stat:
      path: /etc/CommVaultRegistry/Galaxy/Instance001/Session/.properties
    register: prop_file
    tags: install

  - name: Set Commvault chatter flag
    become: yes
    lineinfile:
      path: /etc/CommVaultRegistry/Galaxy/Instance001/Session/.properties
      regexp: '^nChatterFlag'
      line: 'nChatterFlag 0'
      owner: root
      group: root
      mode: 0775
    when: prop_file.stat.exists == true
    tags: install

  - name: Check status of cvpkgchg
    stat:
      path: /opt/commvault/Base/cvpkgchg
    register: cvpkg_exists
    tags: install, fix_perms

  - name: Run commvault cvpkgchg command (Hana DB Servers)
    become: yes
    command: "/opt/commvault/Base/cvpkgchg -i Instance001 -g sapsys -p 775"
    register: cmdResult
    failed_when: cmdResult.rc != 0
    when:
      - ('tag_AnsibleRoles_sap-hana' in group_names)
      - cvpkg_exists.stat is defined
      - cvpkg_exists.stat.exists
    tags: fix_perms,install

  - name: Check if /opt/commvault exists
    stat:
      path: /opt/commvault
    register: opt_commvault
    tags: fix_perms,install

  - name: Fix /opt/commvault permissions (Hana DB Servers)
    become: yes
    file:
      path: /opt/commvault
      mode: 0755
      owner: root
      group: sapsys
    when:
      - ('tag_AnsibleRoles_sap-hana' in group_names)
      - opt_commvault.stat is defined
      - opt_commvault.stat.exists == true
    tags: fix_perms,install

  - name: Run commvault cvpkgchg command (Oracle DB Servers)
    become: yes
    command: "/opt/commvault/Base/cvpkgchg -i Instance001 -g oinstall -p 775"
    register: cmdResult
    failed_when: cmdResult.rc != 0
    when:
      - ('tag_AnsibleRoles_oracle-database' in group_names)
      - cvpkg_exists.stat is defined
      - cvpkg_exists.stat.exists
    tags: fix_perms,install

  - name: fix /opt/commvault permissions (Oracle DB Servers)
    become: yes
    file:
      path: /opt/commvault
      mode: 0775
      owner: root
      group: oinstall
    when:
      - ('tag_AnsibleRoles_oracle-database' in group_names)
      - opt_commvault.stat.exists == true
    tags: fix_perms,install

  handlers:

  - name: start commvault
    become: yes
    service:
      name: commvault
      state: restarted
